CREATE DATABASE IF NOT EXISTS lol1;
CREATE USER IF NOT EXISTS 'ss'@'%' IDENTIFIED BY 'tt' ;
GRANT ALL PRIVILEGES ON lol1.* TO 'ss'@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;
